apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /second
        pathType: Prefix
        backend:
          service:
            name: flask2
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask2
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: flask2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask2
  template:
    metadata:
      labels:
        app: flask2
    spec:
      containers:
      - name: flask2
        image: kostasmathioudakis/hw3:latest
        env:
        - name: MESSAGE
          value: "This is the second service!"
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
