name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build the docker image and push to repo
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Github packages login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build & Push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          tags: kostasmathioudakis/cs548-nginx:latest
          file: ./Dockerfile
          push: true

      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest}}
